### ISSUE TITLE
Errors upon executing client.py

### ISSUE THREAD

**Issue by dr4lekhine** [machine1337/TelegramRAT#4]
Hello, 

First of all, kudos for your project.

I´m facing this error when I try to execute python client.py on Windows (tried with 2 computers):

"
_Failed to delete message. Status code:
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\TelegramRAT\client.py", line 169, in <module>
    main()
  File "C:\Users\Admin\Desktop\TelegramRAT\client.py", line 163, in main
    offset = handle_updates(updates) + 1
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\TelegramRAT\client.py", line 142, in handle_updates
    result = execute_command(message_text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\TelegramRAT\client.py", line 118, in execute_command
    return result.decode('utf-8').strip()
           ^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 13: invalid start byte_
"

![image](https://github.com/machine1337/TelegramRAT/assets/72524642/adfbd686-2213-4bc6-b97f-379ff07ec570)

Lines 16 & 17 of client.py looks like this:

![image](https://github.com/machine1337/TelegramRAT/assets/72524642/2288d3ee-988d-4cd5-8ec8-ad164884779a)

Are you able to determine what could be wrong?. I don´t have any security solution running on that box. I also tried with 2 different Windows boxes.

Reference:
Windows 10 22H2
Python 3.11.0

List of packages installed:
C:\Users\Admin\Desktop\TelegramRAT>pip3 list installed
Package                   Version
------------------------- ---------
altgraph                  0.17.3
certifi                   2023.7.22
charset-normalizer        3.2.0
colorama                  0.4.6
coloramma                 4.5
idna                      3.4
pefile                    2023.2.7
pip                       23.2.1
**pygrabshot                1.0.2**
pyinstaller               5.13.0
pyinstaller-hooks-contrib 2023.6
pywin32-ctypes            0.2.2
**requests                  2.31.0**
setuptools                65.5.0
strcolored                2.0
termcolor                 2.3.0
urllib3                   2.0.4

Thanks in advance.

Regards.

**Comment by dr4lekhine** [comment]
> Hello,
> 
> First of all, kudos for your project.
> 
> I´m facing this error when I try to execute python client.py on Windows (tried with 2 computers):
> 
> " _Failed to delete message. Status code: Traceback (most recent call last): File "C:\Users\Admin\Desktop\TelegramRAT\client.py", line 169, in main() File "C:\Users\Admin\Desktop\TelegramRAT\client.py", line 163, in main offset = handle_updates(updates) + 1 ^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Admin\Desktop\TelegramRAT\client.py", line 142, in handle_updates result = execute_command(message_text) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Admin\Desktop\TelegramRAT\client.py", line 118, in execute_command return result.decode('utf-8').strip() ^^^^^^^^^^^^^^^^^^^^^^ UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 13: invalid start byte_ "
> 
> ![image](https://user-images.githubusercontent.com/72524642/258598785-adfbd686-2213-4bc6-b97f-379ff07ec570.png)
> 
> Lines 16 & 17 of client.py looks like this:
> 
> ![image](https://user-images.githubusercontent.com/72524642/258598859-2288d3ee-988d-4cd5-8ec8-ad164884779a.png)
> 
> Are you able to determine what could be wrong?. I don´t have any security solution running on that box. I also tried with 2 different Windows boxes.
> 
> Reference: Windows 10 22H2 Python 3.11.0
> 
> List of packages installed: C:\Users\Admin\Desktop\TelegramRAT>pip3 list installed Package Version
> 
> altgraph 0.17.3 certifi 2023.7.22 charset-normalizer 3.2.0 colorama 0.4.6 coloramma 4.5 idna 3.4 pefile 2023.2.7 pip 23.2.1 **pygrabshot 1.0.2** pyinstaller 5.13.0 pyinstaller-hooks-contrib 2023.6 pywin32-ctypes 0.2.2 **requests 2.31.0** setuptools 65.5.0 strcolored 2.0 termcolor 2.3.0 urllib3 2.0.4
> 
> Thanks in advance.
> 
> Regards.

Hi,

I managed to get to work in Windows upon uninstallation and reinstallation of pygrabshot (as administator).


Regards.

**Comment by machine1337** [comment]
@dr4lekhine make sure your telegram is working in your country...join this link and send a message https://t.me/machine1337
